apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Manoj-Paramsetti/kubernetes-sample-ctx.git
    targetRevision: main
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
